version: '3.8'
name: 'discordrm'
services:
  postgres-db:
    image: postgres
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    ports:
      - '${PG_PORT}:${PG_PORT}'
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}

  redis-master:
    image: redis
    volumes:
      - redis-data:/var/lib/redis/data
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    command: >
      --requirepass ${REDIS_PASSWORD}

volumes:
  pgsql-data:
  redis-data:
