version: '3.8'
name: 'discordrm'
services:
  postgres-db:
    image: postgres
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    ports:
      - '${PG_PORT}:${PG_PORT}'
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}

volumes:
  pgsql-data:
